# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_auto_20180817_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='ceco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
