# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0009_auto_20180817_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_orden', models.CharField(max_length=100)),
            ],
        ),
    ]
