# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0010_tipoorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tipo_orden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturas.TipoOrden'),
            preserve_default=False,
        ),
    ]
