# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0011_orden_tipo_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Mes'),
        ),
    ]
