# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0012_auto_20180820_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='descripcion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
