# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0014_auto_20180820_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='confiactual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturas.Configuracion'),
            preserve_default=False,
        ),
    ]
