# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField()),
                ('is_bodega', models.BooleanField()),
                ('is_planificador', models.BooleanField()),
                ('is_factura', models.BooleanField()),
                ('is_papeleria', models.BooleanField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Colaborador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
