# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_auto_20180731_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Colaborador',
        ),
    ]
