# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20180731_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='is_bodega',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='is_factura',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='is_papeleria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='is_planificador',
            field=models.BooleanField(default=False),
        ),
    ]
