# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_auto_20180806_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceso',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='is_bodega',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='is_factura',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='is_papeleria',
        ),
        migrations.RemoveField(
            model_name='acceso',
            name='is_planificador',
        ),
        migrations.AddField(
            model_name='acceso',
            name='tipo_acceso',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
