# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0006_auto_20180806_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='tipo_acceso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='central.Acceso'),
            preserve_default=False,
        ),
    ]
