# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0007_colaborador_tipo_acceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='tipo_acceso',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_acceso',
            field=models.ManyToManyField(to='central.Acceso'),
        ),
    ]
