# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0008_auto_20180807_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='tipo_acceso',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_acceso',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='central.Acceso'),
            preserve_default=False,
        ),
    ]
